# Generated by Django 2.2.12 on 2020-07-01 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategy', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('browse_nums', models.IntegerField(default=0, null=True, verbose_name='浏览数')),
                ('collection', models.IntegerField(default=0, null=True, verbose_name='收藏数')),
                ('good', models.IntegerField(default=0, null=True, verbose_name='赞')),
                ('content', models.TextField()),
                ('comments', models.IntegerField(default=0, null=True, verbose_name='评论数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'article',
            },
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(max_length=20, unique=True, verbose_name='文章类型')),
                ('is_delete', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'articletype',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('good', models.IntegerField(verbose_name='赞')),
                ('send_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_delete', models.BooleanField(default=0)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('good', models.IntegerField(verbose_name='赞')),
                ('is_delete', models.BooleanField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_id', to='community.Comment')),
                ('replyuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_replay', to='user.User')),
                ('touser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='user.User')),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=0)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_article', to='community.Article')),
                ('strategy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection_strategy', to='strategy.Strategy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='user.User')),
            ],
            options={
                'db_table': 'collection',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ArticleType'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
